config/routes.rb
Rails.application.routes.draw do
    
  get 'sessions/new'
  
  root 'login#new'
  get 'login/index'

  get    '/login',   to: 'login#new'
  post   '/login',   to: 'login#create'
  delete '/logout',  to: 'login#destroy'

  namespace :admin do
    resources :employees
    resources :users do
      resources :employees
      get 'profile', to: 'users#profile', as: 'profile'   
    end
    resources :positions
    resources :departments
    resources :religions
    resources :educations
    resources :genders
    resources :suppliers
    resources :stations
    resources :items
    resources :item_categories
    resources :item_units
    resources :purchase_requests do
      resources :purchase_orders
    end
    resources :purchase_orders do
      resources :fund_administrations
    end
    resources :purchase_order_addresses
    resources :foods
    resources :food_menus
    resources :fund_administrations
    resources :cycles
    resources :flight_classes
    resources :flight_types
    resources :standard_recipes

    get 'dashboard_administrator', to: 'dashboard#index_administrator', as: 'administrator_dash'
    get 'dashboard_kitchen', to: 'dashboard#index_kitchen', as: 'kitchen_dash'
    get 'dashboard_quality_control', to: 'dashboard#index_quality_control', as: 'quality_control_dash'
    get 'dashboard_logistik', to: 'dashboard#index_logistik', as: 'logistik_dash'
    get 'dashboard_administrasi', to: 'dashboard#index_administrasi', as: 'administrasi_dash'
    get 'dashboard_admin', to: 'dashboard#index_admin', as: 'admin_dash'

    patch 'rekomendasikan_pr/:id', to: "purchase_requests#accept_pr", as: :rekomendasikan_pr
    patch 'tolak_pr/:id', to: "purchase_requests#reject_pr", as: :tolak_pr
    patch 'pencatatan_dana/:id', to: "fund_administrations#create", as: :pencatatan_dana

    get 'purchase_request/:id/tolak_request', to: 'purchase_requests#reject_pr',as: 'reject_pr'
    patch 'purchase_request/:id/tolak_request', to: 'purchase_requests#reject_pr_update',as: 'reject_pr_update'

    get 'purchase_request/:id/terbitkan_purchase_order', to: 'purchase_requests#publish_po',as: 'publish_po'
  end


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/religion.rb
class Religion < ApplicationRecord
	has_many :employees

	validates :name, :presence => {message: "Agama harus di isi !!"}
end

app/controllers/admin/religions_controller.rb
class Admin::ReligionsController < AdminController
  before_action :set_religion, only: [:show, :edit, :update, :destroy]

  # GET /religions
  def index
    @religions = Religion.all
  end

  # GET /religions/new
  def new
    @religion = Religion.new
  end

  # GET /religions/1/edit
  def edit
  end

  # POST /religions
  def create
    @religion = Religion.new(religion_params)
    if @religion.save
      flash[:success] = 'Agama berhasil di tambah'
      redirect_to admin_religions_path
    else
      flash.now[:danger] = 'Agama gagal di tambah'
      @model = @religion
      render :new
    end
  end

  # PATCH/PUT /religions/1
  def update
    if @religion.update(religion_params)
      flash[:success] = 'Agama berhasil di update'
      redirect_to admin_religions_path
    else
      @model = @religion
      flash.now[:danger] = 'Agama gagal di update'
      @model = @religion
      render :edit 
    end
  end

  # DELETE /religions/1
  def destroy
    @religion.destroy 
    flash[:success] = 'Agama berhasil di hapus'
    redirect_to admin_religions_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_religion
      @religion = Religion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def religion_params
      params.require(:religion).permit(:name)
    end
end

app/helpers/religions_helper.rb
module ReligionsHelper
end

app/views/admin/religions/_form.html.erb
<%= form_for [:admin, @religion] do |f| %>
  <fieldset>
    <div class="form-group">
    <%= f.label :name, "Agama", class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class:'form-control' %>
    </div>
    </div>
  </fieldset>

    <fieldset>
    <div class="col-sm-2">
    </div>
      <div class="col-sm-10">
        <%= f.submit "Simpan", :class=>"btn btn-primary", class:"btn btn-fill btn-primary" %>
      </div>
  </fieldset>
<% end %>

app/views/admin/religions/edit.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">
                Edit Agama
                <%= link_to 'Kembali', admin_religions_path, class: "btn btn-fill btn-danger pull-right" %>
                </h4>
                <hr>
            </div>
            <div class="content table-responsive table-full-width">
            	<%= render 'form', religion: @religion %>
			</div>
        </div>
    </div>
</div>

app/views/admin/religions/index.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">
                Master Agama
                <%= link_to 'Tambah Agama', new_admin_religion_path, :class=>"btn btn-warning btn-fill pull-right" %>
                  
                </h4>
            </div>
            <div class="content table-responsive table-full-width">
                <table class="table table-hover table-striped">
                  <thead>
                  <tr>
                    <th>Name</th>
                    <th colspan="2"></th>
                  </tr>
                </thead>

                <tbody>
                  <% @religions.each do |religion| %>
                    <tr>
                      <td><%= religion.name %></td>
                      <td><%= link_to 'Edit', edit_admin_religion_path(religion),class:'text-info' %></td>
                      <td><%= link_to 'Hapus', admin_religion_path(religion), method: :delete, class:'text-danger', data: { confirm: 'Yakin hapus data?' } %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
        </div>
    </div>
</div>

app/views/admin/religions/new.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">
                Tambah Agama
                <%= link_to 'Kembali', admin_religions_path, class: "btn btn-fill btn-danger pull-right" %>
                </h4>
                <hr>
            </div>
            <div class="content table-responsive table-full-width">
`				<%= render 'form', religion: @religion %>
			</div>
        </div>
    </div>
</div>