config/routes.rb
Rails.application.routes.draw do
    
  get 'sessions/new'
  
  root 'login#new'
  get 'login/index'

  get    '/login',   to: 'login#new'
  post   '/login',   to: 'login#create'
  delete '/logout',  to: 'login#destroy'

  namespace :admin do
    resources :employees
    resources :users do
      resources :employees
      get 'profile', to: 'users#profile', as: 'profile'   
    end
    resources :positions
    resources :departments
    resources :religions
    resources :educations
    resources :genders
    resources :suppliers
    resources :stations
    resources :items
    resources :item_categories
    resources :item_units
    resources :purchase_requests do
      resources :purchase_orders
    end
    resources :purchase_orders do
      resources :fund_administrations
    end
    resources :purchase_order_addresses
    resources :foods
    resources :food_menus
    resources :fund_administrations
    resources :cycles
    resources :flight_classes
    resources :flight_types
    resources :standard_recipes

    get 'dashboard_administrator', to: 'dashboard#index_administrator', as: 'administrator_dash'
    get 'dashboard_kitchen', to: 'dashboard#index_kitchen', as: 'kitchen_dash'
    get 'dashboard_quality_control', to: 'dashboard#index_quality_control', as: 'quality_control_dash'
    get 'dashboard_logistik', to: 'dashboard#index_logistik', as: 'logistik_dash'
    get 'dashboard_administrasi', to: 'dashboard#index_administrasi', as: 'administrasi_dash'
    get 'dashboard_admin', to: 'dashboard#index_admin', as: 'admin_dash'

    patch 'rekomendasikan_pr/:id', to: "purchase_requests#accept_pr", as: :rekomendasikan_pr
    patch 'tolak_pr/:id', to: "purchase_requests#reject_pr", as: :tolak_pr
    patch 'pencatatan_dana/:id', to: "fund_administrations#create", as: :pencatatan_dana

    get 'purchase_request/:id/tolak_request', to: 'purchase_requests#reject_pr',as: 'reject_pr'
    patch 'purchase_request/:id/tolak_request', to: 'purchase_requests#reject_pr_update',as: 'reject_pr_update'

    get 'purchase_request/:id/terbitkan_purchase_order', to: 'purchase_requests#publish_po',as: 'publish_po'
  end


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/sidebar/_admin_sidebar.html.erb
<%= sidemenu admin_administrasi_dash_path, "Dashboard", "pe-7s-graph" %>
    <%# Profile Pegawai %>
    <li>
        <a href="<%= admin_user_profile_path(current_user) %>">
            <i class="pe-7s-user"></i>
            <p>User Profile</p>
        </a>
    </li>
    
<%# Menu data pegawai %>
    <li>
        <a data-toggle="collapse" href="#employeeMenu" class="collapsed" aria-expanded="false">
            <i class="pe-7s-users"></i>
            <p>Employee
                <b class="caret"></b>
            </p>
        </a>
        <div class="collapse" id="employeeMenu" aria-expanded="false" style="height: auto;">
            <ul class="nav subnav">
                <li class="<%= active_class admin_users_path %>">
                    <%= link_to 'User Account', admin_users_path %>
                </li>
                <li class="<%= active_class admin_employees_path %>">
                    <%= link_to "Pegawai", admin_employees_path %>
                </li>
            </ul>
        </div>
    </li>
    <%# Menu data master %>
    <li>
        <a data-toggle="collapse" href="#formsExamples" class="collapsed" aria-expanded="false">
            <i class="pe-7s-server"></i>
            <p>Master
               <b class="caret"></b>
            </p>
        </a>
        <div class="collapse" id="formsExamples" aria-expanded="false" style="height: auto;">
            <ul class="nav subnav">
                <li class="<%= active_class admin_religions_path %>">
                    <%= link_to 'Agama', admin_religions_path %>
                </li>
                <li class="<%= active_class admin_genders_path %>">
                    <%= link_to 'Gender', admin_genders_path %>
                </li>
                <li class="<%= active_class admin_educations_path %>">
                    <%= link_to 'Pendidikan', admin_educations_path %>
                </li>
                <li class="<%= active_class admin_positions_path %>">
                    <%= link_to 'Posisi / Jabatan', admin_positions_path %>
                </li>
                <li><%= link_to 'Station', admin_stations_path %></li>
                <li class="<%= active_class admin_departments_path %>">
                    <%= link_to 'Departemen', admin_departments_path %>
                </li>
                <li class="<%= active_class admin_cycles_path %>">
                    <%= link_to 'Cycle', admin_cycles_path %>
                </li>
                <li class="<%= active_class admin_flight_classes_path %>">
                    <%= link_to 'Flight Class', admin_flight_classes_path %>
                </li>
                <li class="<%= active_class admin_flight_types_path %>">
                    <%= link_to 'Flight Type', admin_flight_types_path %>
                </li>
                <li><a href="forms/regular.html">Penyimpanan</a></li>
                <li><a href="#">Pesawat</a></li>
                <li><a href="#">Kwitansi</a></li>
                <li><a href="#">Menu</a></li>
                <li><a href="forms/regular.html">User</a></li>
            </ul>
        </div>
    </li>
    <%# Menu data item %>
    <li>
        <a data-toggle="collapse" href="#itemMenu" class="collapsed" aria-expanded="false">
            <i class="pe-7s-box2"></i>
            <p>Item <b class="caret"></b></p>
        </a>
        <div class="collapse" id="itemMenu" aria-expanded="false" style="height: auto;">
            <ul class="nav subnav">
                <li class="<%= active_class admin_suppliers_path %>" >
                    <%= link_to 'Supplier', admin_suppliers_path %>
                </li>
                <li class="<%= active_class admin_items_path %>" >
                    <%= link_to 'Item', admin_items_path %>
                </li>
                <li class="<%= active_class admin_item_categories_path %>">
                    <%= link_to 'Kategori Barang', admin_item_categories_path %>
                </li>
                <li class="<%= active_class admin_item_units_path %>">
                    <%= link_to 'Satuan Barang', admin_item_units_path %>
                </li>
            
            </ul>
        </div>
    </li>
    <%# Data Standard Recipe %>
    <li class="active_class admin_standard_recipes_path">
        <a href="<%= admin_standard_recipes_path%>">
            <i class="pe-7s-coffee"></i>
            <p>Standard Recipe</p>
        </a>
    </li>
    <li>
        <a data-toggle="collapse" href="#purchaseRequest" class="collapsed" aria-expanded="false">
            <i class="pe-7s-note2"></i>
            <p>Purchase Request <b class="caret"></b></p>
        </a>
        <div class="collapse" id="purchaseRequest" aria-expanded="false" style="height: auto;">
            <ul class="nav subnav">
                <li class="<%= active_class new_admin_purchase_request_path %>" >
                    <%= link_to 'Add Request', new_admin_purchase_request_path %>
                </li>
                <li class="<%= active_class admin_purchase_requests_path %>" >
                    <%= link_to 'Purchase Request', admin_purchase_requests_path %>
                </li>
            
            </ul>
        </div>
    </li>
    <li>
        <a data-toggle="collapse" href="#poMenu" class="collapsed" aria-expanded="false">
            <i class="pe-7s-ticket"></i>
            <p>Purchase Order <b class="caret"></b></p>
        </a>
        <div class="collapse" id="poMenu" aria-expanded="false" style="height: auto;">
            <ul class="nav subnav">
                <li class="<%= active_class admin_purchase_orders_path %>" >
                    <%= link_to 'Purchase Order', admin_purchase_orders_path %>
                </li>
                <li class="<%= active_class admin_purchase_order_addresses_path %>" >
                    <%= link_to 'Alamat Purcahse Order', admin_purchase_order_addresses_path %>
                </li>
            
            </ul>
        </div>
    </li>
    <li class="active_class admin_fund_administrations_path">
        <a href="<%= admin_fund_administrations_path%>">
            <i class="pe-7s-note"></i>
            <p>Pencatatan Dana</p>
        </a>
    </li>
    <li>
      <a data-toggle="collapse" href="#qualityControl" class="collapsed" aria-expanded="false">
        <i class="pe-7s-news-paper"></i>
        <p>Quality Control
           <b class="caret"></b>
        </p>
      </a>
      <div class="collapse" id="qualityControl" aria-expanded="false" style="height: auto;">
        <ul class="nav subnav">
            <li><a href="forms/regular.html">Kategori</a></li>
            <li><a href="forms/regular.html">Satuan</a></li>
            <li><a href="forms/regular.html">Penyimpanan</a></li>
            <li><a href="#">Pesawat</a></li>
            <li><a href="#">Kwitansi</a></li>
            <li><a href="#">Menu</a></li>
            <li><a href="forms/regular.html">User</a></li>
        </ul>
      </div>
    </li>
    <li>
        <a href="typography.html">
            <i class="pe-7s-box2"></i>
            <p>Inventory</p>
        </a>
    </li>
    <li>
        <a href="typography.html">
            <i class="pe-7s-folder"></i>
            <p>Report</p>
        </a>
    </li>

app/views/shared/sidebar/_administrasi_sidebar.html.erb
<%= sidemenu admin_administrasi_dash_path, "Dashboard", "pe-7s-graph" %>
    <%# Profile Pegawai %>
    <li class="<%= active_class admin_user_profile_path(current_user) %>">
        <a href="<%= admin_user_profile_path(current_user) %>">
            <i class="pe-7s-user"></i>
            <p>User Profile</p>
        </a>
    </li>
    <li class="<%= active_class admin_purchase_requests_path %>" >
        <a href="<%= admin_purchase_requests_path %>">
            <i class="pe-7s-note2"></i>
            <p>Purchase Request</p>
        </a>
    </li>
    <li class="<%= active_class admin_purchase_orders_path %>">
        <a href="<%= admin_purchase_orders_path %>">
            <i class="pe-7s-ticket"></i>
            <p>Purchase Order</p>
        </a>
    </li>
    <li class="active_class admin_fund_administrations_path">
        <a href="<%= admin_fund_administrations_path%>">
            <i class="pe-7s-note"></i>
            <p>Pencatatan Dana</p>
        </a>
    </li>
    <li class="<%= active_class admin_suppliers_path %>">
        <a href="<%= admin_suppliers_path%>">
            <i class="pe-7s-culture"></i>
            <p>Supplier</p>
        </a>
    </li>
    <%# Data Standard Recipe %>
    <li class="active_class admin_standard_recipes_path">
        <a href="<%= admin_standard_recipes_path%>">
            <i class="pe-7s-coffee"></i>
            <p>Standard Recipe</p>
        </a>
    </li>
    <li class="<%= active_class '#' %>">
        <a href="#">
            <i class="pe-7s-box2"></i>
            <p>Pemakaian Barang</p>
        </a>
    </li>
    <li>
        <a href="#">
            <i class="pe-7s-box1"></i>
            <p>Inventory</p>
        </a>
    </li>

app/views/shared/sidebar/_administrator_sidebar.html.erb
<%= sidemenu admin_administrator_dash_path, "Dashboard", "pe-7s-graph" %>
    <%# Profile Pegawai %>
    <li class="<%= active_class admin_user_profile_path(current_user) %>" >
        <a href="<%= admin_user_profile_path(current_user)%>">
            <i class="pe-7s-user"></i>
            <p>User Profile</p>
        </a>
    </li>
    <li class="<%= active_class admin_employees_path %>" >
        <a href="<%= admin_employees_path%>">
            <i class="pe-7s-users"></i>
            <p>Employee</p>
        </a>
    </li>
    <li class="<%= active_class admin_users_path %>">
        <a href="<%= admin_users_path%>">
            <i class="pe-7s-id"></i>
            <p>User Account</p>
        </a>
    </li>
    <li class="<%= active_class admin_suppliers_path %>">
        <a href="<%= admin_suppliers_path%>">
            <i class="pe-7s-culture"></i>
            <p>Supplier</p>
        </a>
    </li>
    <%# Data Standard Recipe %>
    <li class="active_class admin_standard_recipes_path">
        <a href="<%= admin_standard_recipes_path%>">
            <i class="pe-7s-coffee"></i>
            <p>Standard Recipe</p>
        </a>
    </li>
    <%# Menu data master %>
    <li>
        <a data-toggle="collapse" href="#formsExamples" class="collapsed" aria-expanded="false">
            <i class="pe-7s-server"></i>
            <p>Master
               <b class="caret"></b>
            </p>
        </a>
        <div class="collapse" id="formsExamples" aria-expanded="false" style="height: auto;">
            <ul class="nav subnav">
                <li class="<%= active_class admin_item_categories_path %>">
                    <%= link_to 'Kategori Barang', admin_item_categories_path %>
                </li>
                <li class="<%= active_class admin_item_units_path %>">
                    <%= link_to 'Satuan Barang', admin_item_units_path %>
                </li>
            </ul>
        </div>
    </li>
    <li>
        <a href="#">
            <i class="pe-7s-box1"></i>
            <p>Inventory</p>
        </a>
    </li>
    <li>
        <a href="#">
            <i class="pe-7s-news-paper"></i>
            <p>Invoice</p>
        </a>
    </li>

app/views/shared/sidebar/_kitchen_sidebar.html.erb
<%= sidemenu admin_kitchen_dash_path, "Dashboard", "pe-7s-graph" %>
    <%# Profile Pegawai %>
    <li class="<%= active_class admin_user_profile_path(current_user) %>">
        <a href="<%= admin_user_profile_path(current_user) %>">
            <i class="pe-7s-user"></i>
            <p>User Profile</p>
        </a>
    </li>
	<%# Data Standard Recipe %>
    <li class="active_class admin_standard_recipes_path">
        <a href="<%= admin_standard_recipes_path%>">
            <i class="pe-7s-coffee"></i>
            <p>Standard Recipe</p>
        </a>
    </li>
    <li>
        <a data-toggle="collapse" href="#purchaseRequest" class="collapsed" aria-expanded="false">
            <i class="pe-7s-note2"></i>
            <p>Purchase Request <b class="caret"></b></p>
        </a>
        <div class="collapse" id="purchaseRequest" aria-expanded="false" style="height: auto;">
            <ul class="nav subnav">
                <li class="<%= active_class new_admin_purchase_request_path %>" >
                    <%= link_to 'Add Request', new_admin_purchase_request_path %>
                </li>
                <li class="<%= active_class admin_purchase_requests_path %>" >
                    <%= link_to 'Purchase Request', admin_purchase_requests_path %>
                </li>
            
            </ul>
        </div>
    </li>
    <li>
        <a data-toggle="collapse" href="#formsExamples" class="collapsed" aria-expanded="false">
            <i class="pe-7s-server"></i>
            <p>Master
               <b class="caret"></b>
            </p>
        </a>
        <div class="collapse" id="formsExamples" aria-expanded="false" style="height: auto;">
            <ul class="nav subnav">
                <li class="<%= active_class admin_item_categories_path %>">
                    <%= link_to 'Kategori Barang', admin_item_categories_path %>
                </li>
                <li class="<%= active_class admin_item_units_path %>">
                    <%= link_to 'Satuan Barang', admin_item_units_path %>
                </li>
                <li class="<%= active_class admin_cycles_path %>">
                    <%= link_to 'Cycle', admin_cycles_path %>
                </li>
            </ul>
        </div>
    </li>
    <li class="<%= active_class admin_items_path %>">
        <a href="<%= admin_items_path %>">
            <i class="pe-7s-box2"></i>
            <p>Item</p>
        </a>
    </li>
    <li>
        <a href="#">
            <i class="pe-7s-box1"></i>
            <p>Inventory</p>
        </a>
    </li>

app/views/shared/sidebar/_logistik_sidebar.html.erb
<%= sidemenu admin_logistik_dash_path, "Dashboard", "pe-7s-graph" %>
    <%# Profile Pegawai %>
    <li class="<%= active_class admin_user_profile_path(current_user) %>">
        <a href="<%= admin_user_profile_path(current_user) %>">
            <i class="pe-7s-user"></i>
            <p>User Profile</p>
        </a>
    </li>
    <li class="<%= active_class admin_purchase_requests_path %>" >
        <a href="<%= admin_purchase_requests_path %>">
            <i class="pe-7s-note2"></i>
            <p>Purchase Request</p>
        </a>
    </li>
    <li class="<%= active_class admin_purchase_orders_path %>">
        <a href="<%= admin_purchase_orders_path %>">
            <i class="pe-7s-ticket"></i>
            <p>Purchase Order</p>
        </a>
    </li>
    <li class="<%= active_class admin_suppliers_path %>">
        <a href="<%= admin_suppliers_path%>">
            <i class="pe-7s-culture"></i>
            <p>Supplier</p>
        </a>
    </li>
    <li>
        <a data-toggle="collapse" href="#foodMenu" class="collapsed" aria-expanded="false">
            <i class="pe-7s-coffee"></i>
            <p>Food <b class="caret"></b></p>
        </a>
        <div class="collapse" id="foodMenu" aria-expanded="false" style="height: auto;">
            <ul class="nav subnav">
                <li class="<%= active_class admin_food_menus_path %>" >
                    <%= link_to 'Menu makanan', admin_food_menus_path %>
                </li>
                <li class="<%= active_class admin_foods_path %>" >
                    <%= link_to 'Makanan', admin_foods_path %>
                </li>
            </ul>
        </div>
    </li>
    <li class="<%= active_class admin_items_path %>">
        <a href="<%= admin_items_path %>">
            <i class="pe-7s-box2"></i>
            <p>Barang</p>
        </a>
    </li>
    <li class="<%= active_class '#' %>">
        <a href="#">
            <i class="pe-7s-box2"></i>
            <p>Pemakaian Barang</p>
        </a>
    </li>
    <li>
        <a href="#">
            <i class="pe-7s-box1"></i>
            <p>Inventory</p>
        </a>
    </li>

app/views/shared/sidebar/_operational_sidebar.html.erb
_operational_sidebar.html.erb

app/views/shared/sidebar/_quality_control_sidebar.html.erb
<%= sidemenu admin_quality_control_dash_path, "Dashboard", "pe-7s-graph" %>
    <%# Profile Pegawai %>
    <li class="<%= active_class admin_user_profile_path(current_user) %>">
        <a href="<%= admin_user_profile_path(current_user) %>">
            <i class="pe-7s-user"></i>
            <p>User Profile</p>
        </a>
    </li>
    <li class="<%= active_class admin_purchase_requests_path %>" >
        <a href="<%= admin_purchase_requests_path %>">
            <i class="pe-7s-note2"></i>
            <p>Purchase Request</p>
        </a>
    </li>
    <li class="<%= active_class admin_suppliers_path %>">
        <a href="<%= admin_suppliers_path%>">
            <i class="pe-7s-culture"></i>
            <p>Supplier</p>
        </a>
    </li>
    <li class="<%= active_class admin_food_menus_path %>">
        <a href="<%= admin_food_menus_path%>">
            <i class="pe-7s-coffee"></i>
            <p>Food Menu</p>
        </a>
    </li>
    <li class="<%= active_class '#' %>">
        <a href="#">
            <i class="pe-7s-box2"></i>
            <p>Pemakaian Barang</p>
        </a>
    </li>
    <li>
        <a href="#">
            <i class="pe-7s-box1"></i>
            <p>Inventory</p>
        </a>
    </li>
    <li class="<%= active_class admin_purchase_orders_path %>">
        <a href="<%= admin_purchase_orders_path %>">
            <i class="pe-7s-ticket"></i>
            <p>Purchase Order</p>
        </a>
    </li>