config/routes.rb
Rails.application.routes.draw do
    
  get 'sessions/new'
  
  root 'login#new'
  get 'login/index'

  get    '/login',   to: 'login#new'
  post   '/login',   to: 'login#create'
  delete '/logout',  to: 'login#destroy'

  namespace :admin do
    resources :employees
    resources :users do
      resources :employees
      get 'profile', to: 'users#profile', as: 'profile'   
    end
    resources :positions
    resources :departments
    resources :religions
    resources :educations
    resources :genders
    resources :suppliers
    resources :stations
    resources :items
    resources :item_categories
    resources :item_units
    resources :purchase_requests do
      resources :purchase_orders
    end
    resources :purchase_orders do
      resources :fund_administrations
    end
    resources :purchase_order_addresses
    resources :foods
    resources :food_menus
    resources :fund_administrations
    resources :cycles
    resources :flight_classes
    resources :flight_types
    resources :standard_recipes

    get 'dashboard_administrator', to: 'dashboard#index_administrator', as: 'administrator_dash'
    get 'dashboard_kitchen', to: 'dashboard#index_kitchen', as: 'kitchen_dash'
    get 'dashboard_quality_control', to: 'dashboard#index_quality_control', as: 'quality_control_dash'
    get 'dashboard_logistik', to: 'dashboard#index_logistik', as: 'logistik_dash'
    get 'dashboard_administrasi', to: 'dashboard#index_administrasi', as: 'administrasi_dash'
    get 'dashboard_admin', to: 'dashboard#index_admin', as: 'admin_dash'

    patch 'rekomendasikan_pr/:id', to: "purchase_requests#accept_pr", as: :rekomendasikan_pr
    patch 'tolak_pr/:id', to: "purchase_requests#reject_pr", as: :tolak_pr
    patch 'pencatatan_dana/:id', to: "fund_administrations#create", as: :pencatatan_dana

    get 'purchase_request/:id/tolak_request', to: 'purchase_requests#reject_pr',as: 'reject_pr'
    patch 'purchase_request/:id/tolak_request', to: 'purchase_requests#reject_pr_update',as: 'reject_pr_update'

    get 'purchase_request/:id/terbitkan_purchase_order', to: 'purchase_requests#publish_po',as: 'publish_po'
  end


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/department.rb
class Department < ApplicationRecord
	belongs_to :station, optional: :true
	has_many :positions

	validates :station_id, :presence => {message: "Station harus di isi !!"}
	validates :name, :presence => {message: "Nama Departemen harus di isi !!"}
	validates :manager, :presence => {message: "Nama Manager harus di isi !!"}
end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < AdminController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  def index
    @departments = Department.all
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  def create
    @department = Department.new(department_params)
    if @department.save
      flash[:success] = 'Departemen berhasil di tambah'
      redirect_to admin_departments_path
    else
      flash.now[:danger] = 'Departemen gagal di tambah'
      @model = @department
      render :new
    end
  end

  # PATCH/PUT /departments/1
  def update
    if @department.update(department_params)
      flash[:success] = 'Departemen berhasil di update'
      redirect_to admin_departments_path
    else
      @model = @department
      flash.now[:danger] = 'Departemen gagal di update'
      render :edit 
    end
  end

  # DELETE /departments/1
  def destroy
    @department.destroy 
    flash[:success] = 'Departemen berhasil di hapus'
    redirect_to admin_departments_path 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:station_id, :name, :manager)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/admin/departments/_form.html.erb
<%= form_for [:admin, @department] do |f| %>
  <fieldset>
    <div class="form-group">
      <%= f.label :station_id, "Station", class:"col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.collection_select(:station_id,Station.all,:id,:name,{:prompt => "Pilih Station"}, class:'form-control') %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <div class="form-group">
      <%= f.label :name, "Nama Departemen", class:"col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, class:'form-control' %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <div class="form-group">
      <%= f.label :manager, "Manajer", class:"col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :manager, class:'form-control' %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <div class="col-sm-2">
    </div>
      <div class="col-sm-10">
        <%= f.submit "Simpan", :class=>"btn btn-primary", class:"btn btn-fill btn-primary" %>
      </div>
  </fieldset>
<% end %>

app/views/admin/departments/edit.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">
                Edit Departemen
                <%= link_to 'Kembali', admin_departments_path, class: "btn btn-fill btn-danger pull-right" %>
                </h4>
                <hr>
            </div>
            <div class="content table-responsive table-full-width">
				<%= render 'form', department: @department %>
			</div>
        </div>
    </div>
</div>

app/views/admin/departments/index.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">
                Master Departemen
                <%= link_to 'Tambah Kategori', new_admin_department_path, :class=>"btn btn-warning btn-fill pull-right" %>
                  
                </h4>
            </div>
            <div class="content table-responsive table-full-width">
                <table class="table table-hover table-striped">
                  <thead>
                  <tr>
                    <th>Station</th>
                    <th>Departemen</th>
                    <th>Manager</th>
                    <th colspan="2"></th>
                  </tr>
                </thead>

                <tbody>
                  <% @departments.each do |department| %>
                    <tr>
                      <td><%= department.try(:station).try(:name) %></td>
                      <td><%= department.name %></td>
                      <td><%= department.manager %></td>
                      <td><%= link_to 'Edit', edit_admin_department_path(department),class:'text-info' %></td>
                      <td><%= link_to 'Destroy', admin_department_path(department), method: :delete, class:'text-danger', data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
        </div>
    </div>
</div>

app/views/admin/departments/new.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">
                Tambah Departemen
                <%= link_to 'Kembali', admin_departments_path, class: "btn btn-fill btn-danger pull-right" %>
                </h4>
                <hr>
            </div>
            <div class="content table-responsive table-full-width">
            	<%= render 'form', department: @department %>
			</div>
        </div>
    </div>
</div>