config/routes.rb
Rails.application.routes.draw do
    
  get 'sessions/new'
  
  root 'login#new'
  get 'login/index'

  get    '/login',   to: 'login#new'
  post   '/login',   to: 'login#create'
  delete '/logout',  to: 'login#destroy'

  namespace :admin do
    resources :employees
    resources :users do
      resources :employees
      get 'profile', to: 'users#profile', as: 'profile'   
    end
    resources :positions
    resources :departments
    resources :religions
    resources :educations
    resources :genders
    resources :suppliers
    resources :stations
    resources :items
    resources :item_categories
    resources :item_units
    resources :purchase_requests do
      resources :purchase_orders
    end
    resources :purchase_orders do
      resources :fund_administrations
    end
    resources :purchase_order_addresses
    resources :foods
    resources :food_menus
    resources :fund_administrations
    resources :cycles
    resources :flight_classes
    resources :flight_types
    resources :standard_recipes

    get 'dashboard_administrator', to: 'dashboard#index_administrator', as: 'administrator_dash'
    get 'dashboard_kitchen', to: 'dashboard#index_kitchen', as: 'kitchen_dash'
    get 'dashboard_quality_control', to: 'dashboard#index_quality_control', as: 'quality_control_dash'
    get 'dashboard_logistik', to: 'dashboard#index_logistik', as: 'logistik_dash'
    get 'dashboard_administrasi', to: 'dashboard#index_administrasi', as: 'administrasi_dash'
    get 'dashboard_admin', to: 'dashboard#index_admin', as: 'admin_dash'

    patch 'rekomendasikan_pr/:id', to: "purchase_requests#accept_pr", as: :rekomendasikan_pr
    patch 'tolak_pr/:id', to: "purchase_requests#reject_pr", as: :tolak_pr
    patch 'pencatatan_dana/:id', to: "fund_administrations#create", as: :pencatatan_dana

    get 'purchase_request/:id/tolak_request', to: 'purchase_requests#reject_pr',as: 'reject_pr'
    patch 'purchase_request/:id/tolak_request', to: 'purchase_requests#reject_pr_update',as: 'reject_pr_update'

    get 'purchase_request/:id/terbitkan_purchase_order', to: 'purchase_requests#publish_po',as: 'publish_po'
  end


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
	belongs_to :purchase_request, optional: true
	belongs_to :purchase_order_address, optional: true
	before_create :generate_po_number, on: :create
	before_save :status_po, on: [:edit, :update]

	validates :purchase_request_id, :uniqueness => {message: "Sudah ada !!"}

	def generate_po_number
		@lpn = PurchaseOrder.last.po_number[9..15]
		self.po_number = "PO-#{DateTime.now.strftime('%y%m%e')}"+(@lpn.to_i + 1).to_s.rjust(7, '0')
	end

	def status_po
		self.status = ''
	end
end

app/controllers/admin/purchase_orders_controller.rb
class Admin::PurchaseOrdersController < AdminController
  before_action :set_pr, on: [:new, :create]
  before_action :set_purchase_order, only: [:show, :edit, :update, :destroy]

  # GET /purchase_orders
  def index
    @purchase_orders = PurchaseOrder.all
  end

  # GET /purchase_orders/1
  def show
  end

  # GET /purchase_orders/new
  def new
    if @pr
      @purchase_order = @pr.purchase_orders.new
    else
      @purchase_order = PurchaseOrder.new
    end
  end

  # GET /purchase_orders/1/edit
  def edit
  end

  # POST /purchase_orders
  def create
    @purchase_order = PurchaseOrder.new(purchase_order_params)

    @purchase_order.purchase_request_id = @pr.id
    if @purchase_order.save
      flash[:success] = 'Purchase Order berhasil di tambah'
      redirect_to admin_purchase_orders_path
    else
      flash.now[:danger] = 'Purchase Order gagal di tambah'
      @model = @purchase_order
      render :new
    end
  end

  # PATCH/PUT /purchase_orders/1
  def update
    if @purchase_order.update(purchase_order_params)
      flash[:success] = 'Purchase Order berhasil di update'
      redirect_to admin_purchase_orders_path
    else
      @model = @purchase_order
      flash.now[:danger] = 'Purchase Order gagal di update'
      render :edit 
    end
  end

  # DELETE /purchase_orders/1
  def destroy
    @purchase_order.destroy 
    flash[:success] = 'Purchase Order berhasil di hapus'
    redirect_to admin_purchase_orders_path 
  end

  private
    def set_pr
      @pr = PurchaseRequest.find(params[:purchase_request_id]) if params[:purchase_request_id]
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase_order
      if params[:purchase_order_id]
        @purchase_order = PurchaseOrder.find(params[:purchase_order_id])
      else
        @purchase_order = PurchaseOrder.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_order_params
      params.require(:purchase_order).permit(:purchase_request_id, :purchase_order_address_id, :po_number, :arrival_estimated, :status)
    end
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/views/admin/purchase_orders/_form.html.erb
<%= form_for [:admin,@pr, @purchase_order] do |f| %>

<fieldset>
  <div class="form-group">
    <%= f.label :purchase_request_id,class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
    <% if @pr.present? %>
      #<%= @pr.pr_number %>
      <% else %>
      #<%= @purchase_order.purchase_request.pr_number %>
    <% end %>
    <%#= f.text_field :purchase_request_id, class:'form-control' %>
    </div>
  </div>
</fieldset>


<fieldset>
  <div class="form-group">
    <%= f.label :purchase_order_address_id, "Alamat PO",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      
      <%= f.collection_select(:purchase_order_address_id,PurchaseOrderAddress.all,:id,:alamat_po,{:prompt => "Pilih Alamat PO"}, class:'form-control') %>
    </div>
  </div>
</fieldset>

<fieldset>
  <div class="form-group">
    <%= f.label :arrival_estimated, "Estimasi kedatangan barang",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :arrival_estimated, class:'form-control' %>
    </div>
  </div>
</fieldset>

<fieldset>
  <div class="form-group">
    <%= f.label :status, "Status",class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :status, class:'form-control' %>
    </div>
  </div>
</fieldset>

  <fieldset>
    <div class="col-sm-2">
    </div>
      <div class="col-sm-10">
        <%= f.submit "Simpan", :class=>"btn btn-primary", class:"btn btn-fill btn-primary" %>
      </div>
  </fieldset>
<% end %>

app/views/admin/purchase_orders/edit.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">
                Edit Purchase Order
                <%= link_to 'Kembali', admin_purchase_orders_path, class: "btn btn-fill btn-danger pull-right" %>
                </h4>
                <hr>
            </div>
            <div class="content table-responsive table-full-width">
				<%= render 'form', purchase_order: @purchase_order %>
            </div>
        </div>
    </div>
</div>

app/views/admin/purchase_orders/index.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">
                Purchase Order
                <%= link_to 'Tambah PO', admin_purchase_requests_path, :class=>"btn btn-warning btn-fill pull-right" if !current_user_quality_control %>
                </h4>
            </div>
            <div class="content table-responsive table-full-width">
                <table class="table table-hover table-striped">
                <thead>
                  <tr>
                    <th>No. PR</th>
                    <th>Alamat Purchase order</th>
                    <th>No. PO</th>
                    <th>Estimasi kedatangan</th>
                    <th>Status</th>
                    <th colspan="3"></th>
                  </tr>
                </thead>

                <tbody>
                  <% @purchase_orders.each do |purchase_order| %>
                    <tr>
                      <td>
                        <code>
                          <%= link_to purchase_order.purchase_request.pr_number, admin_purchase_request_path(purchase_order.purchase_request), class: 'text-danger' %>
                        </code>
                      </td>
                      <td><%= link_to purchase_order.purchase_order_address.try(:name), admin_purchase_order_address_path(purchase_order.purchase_order_address), style: 'color: black' %></td>
                      <td>
                        <code>
                          <%= link_to "#{purchase_order.po_number}", admin_purchase_order_path(purchase_order), class: 'text-success' %>
                        </code>
                      </td>
                      <td><%= purchase_order.arrival_estimated.try(:strftime ,'%d %B %Y %H:%M %p') %></td>
                      <td><%= cekpo(purchase_order.status) %></td>
                      <% if !current_user_quality_control %>
                      <td><%= link_to 'Edit', edit_admin_purchase_order_path(purchase_order) %></td>
                      <td><%= link_to 'Hapus', admin_purchase_order_path(purchase_order), method: :delete, data: { confirm: 'Yakin hapus data?' } %></td>
                      <% end %>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
        </div>
    </div>
</div>

app/views/admin/purchase_orders/new.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">
                Tambah Purchase Order
                <%= link_to 'Kembali', admin_purchase_orders_path, class: "btn btn-fill btn-danger pull-right" %>
                </h4>
                <hr>
            </div>
            <div class="content table-responsive table-full-width">
				<%= render 'form', purchase_order: @purchase_order %>
            </div>
        </div>
    </div>
</div>

app/views/admin/purchase_orders/show.html.erb
<div class="row">
  <div class="panel panel-default nobreakinside">
    <div class="panel-body">
      <div class="col-sm-4">
              Diminta oleh : <strong><%= @purchase_order.purchase_request.employee.name %></strong><br>
              Posisi : <strong><%= @purchase_order.purchase_request.employee.position.name %></strong><br>
              Departemen : <strong><%= @purchase_order.purchase_request.employee.position.department.name %></strong><br>
              Manajer Departemen : <strong><%= @purchase_order.purchase_request.employee.position.department.manager %></strong>
            </div>
            <div class="col-sm-4">
              No. PO : <strong><%= @purchase_order.po_number %></strong><br>
              No. PR : <strong><%= @purchase_order.purchase_request.pr_number %></strong><br>
              Tanggal : <code><strong><%= @purchase_order.purchase_request.date_created.strftime('%d %B %Y') %></strong></code><br>
              Status : <%= cekpo(@purchase_order.status) %>
            </div>
            <div class="col-sm-4">
             <%= link_to 'Kembali', admin_purchase_orders_path, :class=>"btn btn-warning btn-fill pull-right" %>
            </div>
    </div>
  </div>

<% if @purchase_order.purchase_request.status_desc.present? && @purchase_order.purchase_request.status != true %>
  <div class="panel panel-danger">
  <div class="panel-heading">
    Keterangan:
  </div>
    <div class="panel-body">
        <%= @purchase_order.purchase_request.status_desc%>
    </div>
  </div>
<% end %>

  <div class="panel panel-default">
    <div class="panel-body">   
    <%= link_to 'Print', '#', class:"btn btn-xs btn-warning pull-right" if @purchase_order.purchase_request.status == true & current_user_kitchen & current_user_administrasi & current_user_quality_control %>    
    <h3>List Barang</h3>
      <div class="content table-responsive table-full-width">
        <table class="table table-hover table-striped">
          <thead>  
           <tr>  
            <th>Supplier</th>
            <th>Barang</th>
            <th>Kategori</th>
            <th>price</th>  
            <th>quantity</th>  
            <th class="currency">total</th>
           </tr>  
          </thead>  
          <tbody>  
           <% @purchase_order.purchase_request.purchase_request_details.each do |prd| %>  
            <tr> 
             <td><%= prd.item.supplier.name %></td> 
             <td><%= prd.item.name %></td>
             <td><%= prd.item.item_category.name %></td>
             <td><%= ke_rp(prd.item.price) %></td>
             <td><%= prd.qty %> <%= prd.item.item_unit.name %></td>
             <td class="currency"><%= ke_rp(prd.sub_total) %></td>
            </tr>  
           <% end %>  
           <tr>
             <td colspan="5" class="currency"><strong>TOTAL</strong></td>
             <td class="currency"><%= ke_rp(@purchase_order.purchase_request.total)%></td>
           </tr>
          </tbody>  
         </table>  
      </div> 
       <br><br>
      <%= link_to 'Edit', edit_admin_purchase_order_path(@purchase_order), class:"btn btn-fill btn-primary" %>
      <% if current_user_administrasi && @purchase_order.status != "sudah dibayar" %>
      <%= link_to 'Bayar PO', new_admin_purchase_order_fund_administration_path(@purchase_order), class:"btn btn-fill btn-success pull-right" %>
      <% end %>
    </div>
  </div>

</div>